### ISSUE TITLE
It's more of a request than a issue

### ISSUE THREAD

**Issue by Pizza20** [davidebangelista/Vox-OS#5]
I'm building a thing similar to your goguardian bypass. I was wondering if I could borrow the browser and code editor from you.

**Comment by davidebangelista** [comment]
Sure! However, you need to license it to gpl3.
Vox is a foss software, so you can build upon it, in return, you need to realease source code.

To learn more, see the GPL3 license.

**Comment by Pizza20** [comment]
The source is on my account
How would you like to be credited

**Comment by davidebangelista** [comment]
Just leave my copyright file anywhere

David Ebangelista :: iih09276@gmail.com / Under GPL3
